set  -g base-index       1
setw -g pane-base-index  1
set  -g status-interval  1
set  -g status-keys      vi
set  -g mode-keys        vi

set  -g mouse             on
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  24 
set  -g history-limit     100004

set-option -g status-left-length 50
set-option -g default-terminal "$TERM" 
set -as terminal-features ",xterm-256color:RGB"
set -g renumber-windows on
set -s escape-time 0

# create new.. everything in current pwd
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# window navigation
bind -n S-Left previous-window
bind -n S-Right next-window

# copy mode
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# binds for reordering windows
bind -n C-S-Left swap-window -t -1\; select-window -t -1
bind -n C-S-Right swap-window -t +1\; select-window -t +1

# floating window
bind g if-shell -F '#{==:#{session_name},scratch}' {
    detach-client
} {
    display-popup -d "#{pane_current_path}" -w 60% -h 60% -E "tmux -L popup -f ~/.config/tmux/popup.conf new-session -A -s popup"
}

#GLOBAL ACCENT COLOR
set -g @main_accent "#bae2de"
############################

set -g mode-style "fg=#0c0c0c,bg=#b6b8bb"
set -g message-style "fg=#0c0c0c,bg=#b6b8bb"
set -g message-command-style "fg=#0c0c0c,bg=#b6b8bb"
set -g pane-border-style "fg=#b6b8bb"

set -g pane-active-border-style "fg=#{@main_accent}"

set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#b6b8bb,bg=default"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#0c0c0c,bg=#{@main_accent},bold] #S #[fg=#{@main_accent},bg=default,nobold,nounderscore,noitalics]"

set -g status-right "#[fg=#{@main_accent},bg=default] #{prefix_highlight} #($HOME/.config/tmux/music.sh)#[fg=#0c0c0c,bg=#{@main_accent},bold] #h "

setw -g window-status-activity-style "underscore,fg=#7b7c7e,bg=default"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#7b7c7e,bg=default"

# Inactive windows
setw -g window-status-format "#[fg=#7b7c7e,bg=default]  #I  #W #F  "
setw -g window-status-current-format "#[fg=#b6b8bb,bg=default]#[fg=#0c0c0c,bg=#b6b8bb,bold] #I  #W #F #[fg=#b6b8bb,bg=default,nobold,nounderscore,noitalics]"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'AngryMorrocoy/tmux-neolazygit'
set -g @plugin 'tmux-plugins/tmux-sidebar'


run '~/.config/tmux/plugins/tpm/tpm'
